# Settings

## Build
markdown:			kramdown
highlighter:	rouge
permalink:		/:title/
plugins:			[jekyll-paginate]
paginate:			5

## Repo
repo:					"someDOTgeek/bbs"
repo_id:			"R_kgDOGcRpmQ"

## Info
title:				"some.geek BBS"
icon:					"http://some.geek/sdg.png"
language:			"en"
